"""initial schema

Revision ID: 08c5ecc19465
Revises: 
Create Date: 2026-05-20 15:32:00.797061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c5ecc19465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation_codes', 'group_id')
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=False))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'points')
    op.add_column('invitation_codes', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
