"""remove points from users

Revision ID: 523d8aabcc83
Revises: 08c5ecc19465
Create Date: 2026-05-20 15:34:25.339274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523d8aabcc83'
down_revision: Union[str, Sequence[str], None] = '08c5ecc19465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
