"""add group_id to users

Revision ID: 5e18f3f14f0f
Revises: dabe5ba28b43
Create Date: 2026-05-20 16:54:22.836307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e18f3f14f0f'
down_revision: Union[str, Sequence[str], None] = 'dabe5ba28b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###
