"""update models

Revision ID: 70bc1ce12bfe
Revises: 1258e8962ba2
Create Date: 2026-05-30 00:29:29.416546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bc1ce12bfe'
down_revision: Union[str, Sequence[str], None] = '1258e8962ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poker_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_buy_in', sa.Integer(), nullable=True),
    sa.Column('total_cash_out', sa.Integer(), nullable=True),
    sa.Column('is_balanced', sa.Integer(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('insurance_collected', sa.Integer(), nullable=False),
    sa.Column('insurance_paid_out', sa.Integer(), nullable=False),
    sa.Column('anti_paid_out', sa.Integer(), nullable=False),
    sa.Column('organizer_net', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_games_group_id'), 'poker_games', ['group_id'], unique=False)
    op.create_index(op.f('ix_poker_games_id'), 'poker_games', ['id'], unique=False)
    op.create_table('chip_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['poker_games.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chip_requests_game_id'), 'chip_requests', ['game_id'], unique=False)
    op.create_index(op.f('ix_chip_requests_id'), 'chip_requests', ['id'], unique=False)
    op.create_table('poker_game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('total_buy_in', sa.Integer(), nullable=False),
    sa.Column('cash_out', sa.Integer(), nullable=True),
    sa.Column('insurance_paid', sa.Integer(), nullable=False),
    sa.Column('insurance_received', sa.Integer(), nullable=False),
    sa.Column('anti_received', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['poker_games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poker_game_players_game_id'), 'poker_game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_poker_game_players_id'), 'poker_game_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poker_game_players_id'), table_name='poker_game_players')
    op.drop_index(op.f('ix_poker_game_players_game_id'), table_name='poker_game_players')
    op.drop_table('poker_game_players')
    op.drop_index(op.f('ix_chip_requests_id'), table_name='chip_requests')
    op.drop_index(op.f('ix_chip_requests_game_id'), table_name='chip_requests')
    op.drop_table('chip_requests')
    op.drop_index(op.f('ix_poker_games_id'), table_name='poker_games')
    op.drop_index(op.f('ix_poker_games_group_id'), table_name='poker_games')
    op.drop_table('poker_games')
    # ### end Alembic commands ###
