"""remove points from users

Revision ID: 8a0acdb37e54
Revises: 506641d3f8bd
Create Date: 2026-05-20 13:14:16.885964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0acdb37e54'
down_revision: Union[str, Sequence[str], None] = '506641d3f8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
