"""add group_id to invitation codes

Revision ID: ba563b93d99e
Revises: 8a0acdb37e54
Create Date: 2026-05-20 13:29:12.425844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba563b93d99e'
down_revision: Union[str, Sequence[str], None] = '8a0acdb37e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_codes', sa.Column('group_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation_codes', 'group_id')
    # ### end Alembic commands ###
