"""add group_id to invitation codes

Revision ID: f82eb6040a2a
Revises: 5e18f3f14f0f
Create Date: 2026-05-20 16:57:51.976558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82eb6040a2a'
down_revision: Union[str, Sequence[str], None] = '5e18f3f14f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_codes', sa.Column('group_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation_codes', 'group_id')
    # ### end Alembic commands ###
